/* File: pymdmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Mon Sep 19 11:12:03 2016
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *pymd_error;
static PyObject *pymd_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(pymd_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = pymd_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = pymd_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** lj_pot ***********************************/
static char doc_f2py_rout_pymd_mymd_lj_pot[] = "\
lj_pot = lj_pot(r)\n\nWrapper for ``lj_pot``.\
\n\nParameters\n----------\n"
"r : input float\n"
"\nReturns\n-------\n"
"lj_pot : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_pymd_mymd_lj_pot(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float lj_pot = 0;
  float r = 0;
  PyObject *r_capi = Py_None;
  static char *capi_kwlist[] = {"r",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:pymd.mymd.lj_pot",\
    capi_kwlist,&r_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable lj_pot */
  /* Processing variable r */
    f2py_success = float_from_pyobj(&r,r_capi,"pymd.mymd.lj_pot() 1st argument (r) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&lj_pot,&r);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",lj_pot);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
  /* End of cleaning variable lj_pot */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of lj_pot *******************************/

/********************************** lj_pot2 **********************************/
static char doc_f2py_rout_pymd_mymd_lj_pot2[] = "\
lj_pot2 = lj_pot2(r2)\n\nWrapper for ``lj_pot2``.\
\n\nParameters\n----------\n"
"r2 : input float\n"
"\nReturns\n-------\n"
"lj_pot2 : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_pymd_mymd_lj_pot2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float lj_pot2 = 0;
  float r2 = 0;
  PyObject *r2_capi = Py_None;
  static char *capi_kwlist[] = {"r2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:pymd.mymd.lj_pot2",\
    capi_kwlist,&r2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r2 */
    f2py_success = float_from_pyobj(&r2,r2_capi,"pymd.mymd.lj_pot2() 1st argument (r2) can't be converted to float");
  if (f2py_success) {
  /* Processing variable lj_pot2 */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&lj_pot2,&r2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",lj_pot2);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable lj_pot2 */
  } /*if (f2py_success) of r2*/
  /* End of cleaning variable r2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of lj_pot2 *******************************/

/************************************ Epot ************************************/
static char doc_f2py_rout_pymd_mymd_Epot[] = "\
Epot = Epot(rx,ry,rz,[n])\n\nWrapper for ``Epot``.\
\n\nParameters\n----------\n"
"rx : input rank-1 array('f') with bounds (n)\n"
"ry : input rank-1 array('f') with bounds (n)\n"
"rz : input rank-1 array('f') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(rx)\n"
"\nReturns\n-------\n"
"Epot : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_pymd_mymd_Epot(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float Epot = 0;
  int n = 0;
  PyObject *n_capi = Py_None;
  float *rx = NULL;
  npy_intp rx_Dims[1] = {-1};
  const int rx_Rank = 1;
  PyArrayObject *capi_rx_tmp = NULL;
  int capi_rx_intent = 0;
  PyObject *rx_capi = Py_None;
  float *ry = NULL;
  npy_intp ry_Dims[1] = {-1};
  const int ry_Rank = 1;
  PyArrayObject *capi_ry_tmp = NULL;
  int capi_ry_intent = 0;
  PyObject *ry_capi = Py_None;
  float *rz = NULL;
  npy_intp rz_Dims[1] = {-1};
  const int rz_Rank = 1;
  PyArrayObject *capi_rz_tmp = NULL;
  int capi_rz_intent = 0;
  PyObject *rz_capi = Py_None;
  static char *capi_kwlist[] = {"rx","ry","rz","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|O:pymd.mymd.Epot",\
    capi_kwlist,&rx_capi,&ry_capi,&rz_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rx */
  ;
  capi_rx_intent |= F2PY_INTENT_IN;
  capi_rx_tmp = array_from_pyobj(NPY_FLOAT,rx_Dims,rx_Rank,capi_rx_intent,rx_capi);
  if (capi_rx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 1st argument `rx' of pymd.mymd.Epot to C/Fortran array" );
  } else {
    rx = (float *)(PyArray_DATA(capi_rx_tmp));

  /* Processing variable Epot */
  /* Processing variable n */
  if (n_capi == Py_None) n = len(rx); else
    f2py_success = int_from_pyobj(&n,n_capi,"pymd.mymd.Epot() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(rx)>=n,"len(rx)>=n","1st keyword n","Epot:n=%d",n) {
  /* Processing variable ry */
  ry_Dims[0]=n;
  capi_ry_intent |= F2PY_INTENT_IN;
  capi_ry_tmp = array_from_pyobj(NPY_FLOAT,ry_Dims,ry_Rank,capi_ry_intent,ry_capi);
  if (capi_ry_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 2nd argument `ry' of pymd.mymd.Epot to C/Fortran array" );
  } else {
    ry = (float *)(PyArray_DATA(capi_ry_tmp));

  /* Processing variable rz */
  rz_Dims[0]=n;
  capi_rz_intent |= F2PY_INTENT_IN;
  capi_rz_tmp = array_from_pyobj(NPY_FLOAT,rz_Dims,rz_Rank,capi_rz_intent,rz_capi);
  if (capi_rz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 3rd argument `rz' of pymd.mymd.Epot to C/Fortran array" );
  } else {
    rz = (float *)(PyArray_DATA(capi_rz_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&Epot,&n,rx,ry,rz);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",Epot);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_rz_tmp!=rz_capi) {
    Py_XDECREF(capi_rz_tmp); }
  }  /*if (capi_rz_tmp == NULL) ... else of rz*/
  /* End of cleaning variable rz */
  if((PyObject *)capi_ry_tmp!=ry_capi) {
    Py_XDECREF(capi_ry_tmp); }
  }  /*if (capi_ry_tmp == NULL) ... else of ry*/
  /* End of cleaning variable ry */
  } /*CHECKSCALAR(len(rx)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  /* End of cleaning variable Epot */
  if((PyObject *)capi_rx_tmp!=rx_capi) {
    Py_XDECREF(capi_rx_tmp); }
  }  /*if (capi_rx_tmp == NULL) ... else of rx*/
  /* End of cleaning variable rx */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of Epot ********************************/

/************************************ Ekin ************************************/
static char doc_f2py_rout_pymd_mymd_Ekin[] = "\
Ekin = Ekin(vx,vy,vz,[n])\n\nWrapper for ``Ekin``.\
\n\nParameters\n----------\n"
"vx : input rank-1 array('f') with bounds (n)\n"
"vy : input rank-1 array('f') with bounds (n)\n"
"vz : input rank-1 array('f') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(vx)\n"
"\nReturns\n-------\n"
"Ekin : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_pymd_mymd_Ekin(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float Ekin = 0;
  int n = 0;
  PyObject *n_capi = Py_None;
  float *vx = NULL;
  npy_intp vx_Dims[1] = {-1};
  const int vx_Rank = 1;
  PyArrayObject *capi_vx_tmp = NULL;
  int capi_vx_intent = 0;
  PyObject *vx_capi = Py_None;
  float *vy = NULL;
  npy_intp vy_Dims[1] = {-1};
  const int vy_Rank = 1;
  PyArrayObject *capi_vy_tmp = NULL;
  int capi_vy_intent = 0;
  PyObject *vy_capi = Py_None;
  float *vz = NULL;
  npy_intp vz_Dims[1] = {-1};
  const int vz_Rank = 1;
  PyArrayObject *capi_vz_tmp = NULL;
  int capi_vz_intent = 0;
  PyObject *vz_capi = Py_None;
  static char *capi_kwlist[] = {"vx","vy","vz","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|O:pymd.mymd.Ekin",\
    capi_kwlist,&vx_capi,&vy_capi,&vz_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable vx */
  ;
  capi_vx_intent |= F2PY_INTENT_IN;
  capi_vx_tmp = array_from_pyobj(NPY_FLOAT,vx_Dims,vx_Rank,capi_vx_intent,vx_capi);
  if (capi_vx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 1st argument `vx' of pymd.mymd.Ekin to C/Fortran array" );
  } else {
    vx = (float *)(PyArray_DATA(capi_vx_tmp));

  /* Processing variable Ekin */
  /* Processing variable n */
  if (n_capi == Py_None) n = len(vx); else
    f2py_success = int_from_pyobj(&n,n_capi,"pymd.mymd.Ekin() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(vx)>=n,"len(vx)>=n","1st keyword n","Ekin:n=%d",n) {
  /* Processing variable vy */
  vy_Dims[0]=n;
  capi_vy_intent |= F2PY_INTENT_IN;
  capi_vy_tmp = array_from_pyobj(NPY_FLOAT,vy_Dims,vy_Rank,capi_vy_intent,vy_capi);
  if (capi_vy_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 2nd argument `vy' of pymd.mymd.Ekin to C/Fortran array" );
  } else {
    vy = (float *)(PyArray_DATA(capi_vy_tmp));

  /* Processing variable vz */
  vz_Dims[0]=n;
  capi_vz_intent |= F2PY_INTENT_IN;
  capi_vz_tmp = array_from_pyobj(NPY_FLOAT,vz_Dims,vz_Rank,capi_vz_intent,vz_capi);
  if (capi_vz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 3rd argument `vz' of pymd.mymd.Ekin to C/Fortran array" );
  } else {
    vz = (float *)(PyArray_DATA(capi_vz_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&Ekin,&n,vx,vy,vz);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",Ekin);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_vz_tmp!=vz_capi) {
    Py_XDECREF(capi_vz_tmp); }
  }  /*if (capi_vz_tmp == NULL) ... else of vz*/
  /* End of cleaning variable vz */
  if((PyObject *)capi_vy_tmp!=vy_capi) {
    Py_XDECREF(capi_vy_tmp); }
  }  /*if (capi_vy_tmp == NULL) ... else of vy*/
  /* End of cleaning variable vy */
  } /*CHECKSCALAR(len(vx)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  /* End of cleaning variable Ekin */
  if((PyObject *)capi_vx_tmp!=vx_capi) {
    Py_XDECREF(capi_vx_tmp); }
  }  /*if (capi_vx_tmp == NULL) ... else of vx*/
  /* End of cleaning variable vx */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of Ekin ********************************/

/****************************** lj_force_factor ******************************/
static char doc_f2py_rout_pymd_mymd_lj_force_factor[] = "\
lj_force_factor = lj_force_factor(r2)\n\nWrapper for ``lj_force_factor``.\
\n\nParameters\n----------\n"
"r2 : input float\n"
"\nReturns\n-------\n"
"lj_force_factor : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_pymd_mymd_lj_force_factor(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float lj_force_factor = 0;
  float r2 = 0;
  PyObject *r2_capi = Py_None;
  static char *capi_kwlist[] = {"r2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:pymd.mymd.lj_force_factor",\
    capi_kwlist,&r2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable lj_force_factor */
  /* Processing variable r2 */
    f2py_success = float_from_pyobj(&r2,r2_capi,"pymd.mymd.lj_force_factor() 1st argument (r2) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&lj_force_factor,&r2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",lj_force_factor);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of r2*/
  /* End of cleaning variable r2 */
  /* End of cleaning variable lj_force_factor */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of lj_force_factor ***************************/

/*************************** compute_accelerations ***************************/
static char doc_f2py_rout_pymd_mymd_compute_accelerations[] = "\
compute_accelerations(rx,ry,rz,ax,ay,az,[n])\n\nWrapper for ``compute_accelerations``.\
\n\nParameters\n----------\n"
"rx : input rank-1 array('f') with bounds (n)\n"
"ry : input rank-1 array('f') with bounds (n)\n"
"rz : input rank-1 array('f') with bounds (n)\n"
"ax : in/output rank-1 array('f') with bounds (n)\n"
"ay : in/output rank-1 array('f') with bounds (n)\n"
"az : in/output rank-1 array('f') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(rx)";
/*  */
static PyObject *f2py_rout_pymd_mymd_compute_accelerations(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  float *rx = NULL;
  npy_intp rx_Dims[1] = {-1};
  const int rx_Rank = 1;
  PyArrayObject *capi_rx_tmp = NULL;
  int capi_rx_intent = 0;
  PyObject *rx_capi = Py_None;
  float *ry = NULL;
  npy_intp ry_Dims[1] = {-1};
  const int ry_Rank = 1;
  PyArrayObject *capi_ry_tmp = NULL;
  int capi_ry_intent = 0;
  PyObject *ry_capi = Py_None;
  float *rz = NULL;
  npy_intp rz_Dims[1] = {-1};
  const int rz_Rank = 1;
  PyArrayObject *capi_rz_tmp = NULL;
  int capi_rz_intent = 0;
  PyObject *rz_capi = Py_None;
  float *ax = NULL;
  npy_intp ax_Dims[1] = {-1};
  const int ax_Rank = 1;
  PyArrayObject *capi_ax_tmp = NULL;
  int capi_ax_intent = 0;
  PyObject *ax_capi = Py_None;
  float *ay = NULL;
  npy_intp ay_Dims[1] = {-1};
  const int ay_Rank = 1;
  PyArrayObject *capi_ay_tmp = NULL;
  int capi_ay_intent = 0;
  PyObject *ay_capi = Py_None;
  float *az = NULL;
  npy_intp az_Dims[1] = {-1};
  const int az_Rank = 1;
  PyArrayObject *capi_az_tmp = NULL;
  int capi_az_intent = 0;
  PyObject *az_capi = Py_None;
  static char *capi_kwlist[] = {"rx","ry","rz","ax","ay","az","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|O:pymd.mymd.compute_accelerations",\
    capi_kwlist,&rx_capi,&ry_capi,&rz_capi,&ax_capi,&ay_capi,&az_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rx */
  ;
  capi_rx_intent |= F2PY_INTENT_IN;
  capi_rx_tmp = array_from_pyobj(NPY_FLOAT,rx_Dims,rx_Rank,capi_rx_intent,rx_capi);
  if (capi_rx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 1st argument `rx' of pymd.mymd.compute_accelerations to C/Fortran array" );
  } else {
    rx = (float *)(PyArray_DATA(capi_rx_tmp));

  /* Processing variable n */
  if (n_capi == Py_None) n = len(rx); else
    f2py_success = int_from_pyobj(&n,n_capi,"pymd.mymd.compute_accelerations() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(rx)>=n,"len(rx)>=n","1st keyword n","compute_accelerations:n=%d",n) {
  /* Processing variable ay */
  ay_Dims[0]=n;
  capi_ay_intent |= F2PY_INTENT_INOUT;
  capi_ay_tmp = array_from_pyobj(NPY_FLOAT,ay_Dims,ay_Rank,capi_ay_intent,ay_capi);
  if (capi_ay_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 5th argument `ay' of pymd.mymd.compute_accelerations to C/Fortran array" );
  } else {
    ay = (float *)(PyArray_DATA(capi_ay_tmp));

  /* Processing variable ax */
  ax_Dims[0]=n;
  capi_ax_intent |= F2PY_INTENT_INOUT;
  capi_ax_tmp = array_from_pyobj(NPY_FLOAT,ax_Dims,ax_Rank,capi_ax_intent,ax_capi);
  if (capi_ax_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 4th argument `ax' of pymd.mymd.compute_accelerations to C/Fortran array" );
  } else {
    ax = (float *)(PyArray_DATA(capi_ax_tmp));

  /* Processing variable ry */
  ry_Dims[0]=n;
  capi_ry_intent |= F2PY_INTENT_IN;
  capi_ry_tmp = array_from_pyobj(NPY_FLOAT,ry_Dims,ry_Rank,capi_ry_intent,ry_capi);
  if (capi_ry_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 2nd argument `ry' of pymd.mymd.compute_accelerations to C/Fortran array" );
  } else {
    ry = (float *)(PyArray_DATA(capi_ry_tmp));

  /* Processing variable az */
  az_Dims[0]=n;
  capi_az_intent |= F2PY_INTENT_INOUT;
  capi_az_tmp = array_from_pyobj(NPY_FLOAT,az_Dims,az_Rank,capi_az_intent,az_capi);
  if (capi_az_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 6th argument `az' of pymd.mymd.compute_accelerations to C/Fortran array" );
  } else {
    az = (float *)(PyArray_DATA(capi_az_tmp));

  /* Processing variable rz */
  rz_Dims[0]=n;
  capi_rz_intent |= F2PY_INTENT_IN;
  capi_rz_tmp = array_from_pyobj(NPY_FLOAT,rz_Dims,rz_Rank,capi_rz_intent,rz_capi);
  if (capi_rz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 3rd argument `rz' of pymd.mymd.compute_accelerations to C/Fortran array" );
  } else {
    rz = (float *)(PyArray_DATA(capi_rz_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,rx,ry,rz,ax,ay,az);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_rz_tmp!=rz_capi) {
    Py_XDECREF(capi_rz_tmp); }
  }  /*if (capi_rz_tmp == NULL) ... else of rz*/
  /* End of cleaning variable rz */
  if((PyObject *)capi_az_tmp!=az_capi) {
    Py_XDECREF(capi_az_tmp); }
  }  /*if (capi_az_tmp == NULL) ... else of az*/
  /* End of cleaning variable az */
  if((PyObject *)capi_ry_tmp!=ry_capi) {
    Py_XDECREF(capi_ry_tmp); }
  }  /*if (capi_ry_tmp == NULL) ... else of ry*/
  /* End of cleaning variable ry */
  if((PyObject *)capi_ax_tmp!=ax_capi) {
    Py_XDECREF(capi_ax_tmp); }
  }  /*if (capi_ax_tmp == NULL) ... else of ax*/
  /* End of cleaning variable ax */
  if((PyObject *)capi_ay_tmp!=ay_capi) {
    Py_XDECREF(capi_ay_tmp); }
  }  /*if (capi_ay_tmp == NULL) ... else of ay*/
  /* End of cleaning variable ay */
  } /*CHECKSCALAR(len(rx)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_rx_tmp!=rx_capi) {
    Py_XDECREF(capi_rx_tmp); }
  }  /*if (capi_rx_tmp == NULL) ... else of rx*/
  /* End of cleaning variable rx */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of compute_accelerations ************************/

/**************************** vv_update_positions ****************************/
static char doc_f2py_rout_pymd_mymd_vv_update_positions[] = "\
vv_update_positions(rx,ry,rz,vx,vy,vz,ax,ay,az,dt,[n])\n\nWrapper for ``vv_update_positions``.\
\n\nParameters\n----------\n"
"rx : in/output rank-1 array('f') with bounds (n)\n"
"ry : in/output rank-1 array('f') with bounds (n)\n"
"rz : in/output rank-1 array('f') with bounds (n)\n"
"vx : in/output rank-1 array('f') with bounds (n)\n"
"vy : in/output rank-1 array('f') with bounds (n)\n"
"vz : in/output rank-1 array('f') with bounds (n)\n"
"ax : input rank-1 array('f') with bounds (n)\n"
"ay : input rank-1 array('f') with bounds (n)\n"
"az : input rank-1 array('f') with bounds (n)\n"
"dt : input float\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(rx)";
/*  */
static PyObject *f2py_rout_pymd_mymd_vv_update_positions(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  float *rx = NULL;
  npy_intp rx_Dims[1] = {-1};
  const int rx_Rank = 1;
  PyArrayObject *capi_rx_tmp = NULL;
  int capi_rx_intent = 0;
  PyObject *rx_capi = Py_None;
  float *ry = NULL;
  npy_intp ry_Dims[1] = {-1};
  const int ry_Rank = 1;
  PyArrayObject *capi_ry_tmp = NULL;
  int capi_ry_intent = 0;
  PyObject *ry_capi = Py_None;
  float *rz = NULL;
  npy_intp rz_Dims[1] = {-1};
  const int rz_Rank = 1;
  PyArrayObject *capi_rz_tmp = NULL;
  int capi_rz_intent = 0;
  PyObject *rz_capi = Py_None;
  float *vx = NULL;
  npy_intp vx_Dims[1] = {-1};
  const int vx_Rank = 1;
  PyArrayObject *capi_vx_tmp = NULL;
  int capi_vx_intent = 0;
  PyObject *vx_capi = Py_None;
  float *vy = NULL;
  npy_intp vy_Dims[1] = {-1};
  const int vy_Rank = 1;
  PyArrayObject *capi_vy_tmp = NULL;
  int capi_vy_intent = 0;
  PyObject *vy_capi = Py_None;
  float *vz = NULL;
  npy_intp vz_Dims[1] = {-1};
  const int vz_Rank = 1;
  PyArrayObject *capi_vz_tmp = NULL;
  int capi_vz_intent = 0;
  PyObject *vz_capi = Py_None;
  float *ax = NULL;
  npy_intp ax_Dims[1] = {-1};
  const int ax_Rank = 1;
  PyArrayObject *capi_ax_tmp = NULL;
  int capi_ax_intent = 0;
  PyObject *ax_capi = Py_None;
  float *ay = NULL;
  npy_intp ay_Dims[1] = {-1};
  const int ay_Rank = 1;
  PyArrayObject *capi_ay_tmp = NULL;
  int capi_ay_intent = 0;
  PyObject *ay_capi = Py_None;
  float *az = NULL;
  npy_intp az_Dims[1] = {-1};
  const int az_Rank = 1;
  PyArrayObject *capi_az_tmp = NULL;
  int capi_az_intent = 0;
  PyObject *az_capi = Py_None;
  float dt = 0;
  PyObject *dt_capi = Py_None;
  static char *capi_kwlist[] = {"rx","ry","rz","vx","vy","vz","ax","ay","az","dt","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO|O:pymd.mymd.vv_update_positions",\
    capi_kwlist,&rx_capi,&ry_capi,&rz_capi,&vx_capi,&vy_capi,&vz_capi,&ax_capi,&ay_capi,&az_capi,&dt_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rx */
  ;
  capi_rx_intent |= F2PY_INTENT_INOUT;
  capi_rx_tmp = array_from_pyobj(NPY_FLOAT,rx_Dims,rx_Rank,capi_rx_intent,rx_capi);
  if (capi_rx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 1st argument `rx' of pymd.mymd.vv_update_positions to C/Fortran array" );
  } else {
    rx = (float *)(PyArray_DATA(capi_rx_tmp));

  /* Processing variable dt */
    f2py_success = float_from_pyobj(&dt,dt_capi,"pymd.mymd.vv_update_positions() 10th argument (dt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(rx); else
    f2py_success = int_from_pyobj(&n,n_capi,"pymd.mymd.vv_update_positions() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(rx)>=n,"len(rx)>=n","1st keyword n","vv_update_positions:n=%d",n) {
  /* Processing variable vy */
  vy_Dims[0]=n;
  capi_vy_intent |= F2PY_INTENT_INOUT;
  capi_vy_tmp = array_from_pyobj(NPY_FLOAT,vy_Dims,vy_Rank,capi_vy_intent,vy_capi);
  if (capi_vy_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 5th argument `vy' of pymd.mymd.vv_update_positions to C/Fortran array" );
  } else {
    vy = (float *)(PyArray_DATA(capi_vy_tmp));

  /* Processing variable vz */
  vz_Dims[0]=n;
  capi_vz_intent |= F2PY_INTENT_INOUT;
  capi_vz_tmp = array_from_pyobj(NPY_FLOAT,vz_Dims,vz_Rank,capi_vz_intent,vz_capi);
  if (capi_vz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 6th argument `vz' of pymd.mymd.vv_update_positions to C/Fortran array" );
  } else {
    vz = (float *)(PyArray_DATA(capi_vz_tmp));

  /* Processing variable ay */
  ay_Dims[0]=n;
  capi_ay_intent |= F2PY_INTENT_IN;
  capi_ay_tmp = array_from_pyobj(NPY_FLOAT,ay_Dims,ay_Rank,capi_ay_intent,ay_capi);
  if (capi_ay_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 8th argument `ay' of pymd.mymd.vv_update_positions to C/Fortran array" );
  } else {
    ay = (float *)(PyArray_DATA(capi_ay_tmp));

  /* Processing variable ax */
  ax_Dims[0]=n;
  capi_ax_intent |= F2PY_INTENT_IN;
  capi_ax_tmp = array_from_pyobj(NPY_FLOAT,ax_Dims,ax_Rank,capi_ax_intent,ax_capi);
  if (capi_ax_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 7th argument `ax' of pymd.mymd.vv_update_positions to C/Fortran array" );
  } else {
    ax = (float *)(PyArray_DATA(capi_ax_tmp));

  /* Processing variable ry */
  ry_Dims[0]=n;
  capi_ry_intent |= F2PY_INTENT_INOUT;
  capi_ry_tmp = array_from_pyobj(NPY_FLOAT,ry_Dims,ry_Rank,capi_ry_intent,ry_capi);
  if (capi_ry_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 2nd argument `ry' of pymd.mymd.vv_update_positions to C/Fortran array" );
  } else {
    ry = (float *)(PyArray_DATA(capi_ry_tmp));

  /* Processing variable az */
  az_Dims[0]=n;
  capi_az_intent |= F2PY_INTENT_IN;
  capi_az_tmp = array_from_pyobj(NPY_FLOAT,az_Dims,az_Rank,capi_az_intent,az_capi);
  if (capi_az_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 9th argument `az' of pymd.mymd.vv_update_positions to C/Fortran array" );
  } else {
    az = (float *)(PyArray_DATA(capi_az_tmp));

  /* Processing variable rz */
  rz_Dims[0]=n;
  capi_rz_intent |= F2PY_INTENT_INOUT;
  capi_rz_tmp = array_from_pyobj(NPY_FLOAT,rz_Dims,rz_Rank,capi_rz_intent,rz_capi);
  if (capi_rz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 3rd argument `rz' of pymd.mymd.vv_update_positions to C/Fortran array" );
  } else {
    rz = (float *)(PyArray_DATA(capi_rz_tmp));

  /* Processing variable vx */
  vx_Dims[0]=n;
  capi_vx_intent |= F2PY_INTENT_INOUT;
  capi_vx_tmp = array_from_pyobj(NPY_FLOAT,vx_Dims,vx_Rank,capi_vx_intent,vx_capi);
  if (capi_vx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 4th argument `vx' of pymd.mymd.vv_update_positions to C/Fortran array" );
  } else {
    vx = (float *)(PyArray_DATA(capi_vx_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,rx,ry,rz,vx,vy,vz,ax,ay,az,&dt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_vx_tmp!=vx_capi) {
    Py_XDECREF(capi_vx_tmp); }
  }  /*if (capi_vx_tmp == NULL) ... else of vx*/
  /* End of cleaning variable vx */
  if((PyObject *)capi_rz_tmp!=rz_capi) {
    Py_XDECREF(capi_rz_tmp); }
  }  /*if (capi_rz_tmp == NULL) ... else of rz*/
  /* End of cleaning variable rz */
  if((PyObject *)capi_az_tmp!=az_capi) {
    Py_XDECREF(capi_az_tmp); }
  }  /*if (capi_az_tmp == NULL) ... else of az*/
  /* End of cleaning variable az */
  if((PyObject *)capi_ry_tmp!=ry_capi) {
    Py_XDECREF(capi_ry_tmp); }
  }  /*if (capi_ry_tmp == NULL) ... else of ry*/
  /* End of cleaning variable ry */
  if((PyObject *)capi_ax_tmp!=ax_capi) {
    Py_XDECREF(capi_ax_tmp); }
  }  /*if (capi_ax_tmp == NULL) ... else of ax*/
  /* End of cleaning variable ax */
  if((PyObject *)capi_ay_tmp!=ay_capi) {
    Py_XDECREF(capi_ay_tmp); }
  }  /*if (capi_ay_tmp == NULL) ... else of ay*/
  /* End of cleaning variable ay */
  if((PyObject *)capi_vz_tmp!=vz_capi) {
    Py_XDECREF(capi_vz_tmp); }
  }  /*if (capi_vz_tmp == NULL) ... else of vz*/
  /* End of cleaning variable vz */
  if((PyObject *)capi_vy_tmp!=vy_capi) {
    Py_XDECREF(capi_vy_tmp); }
  }  /*if (capi_vy_tmp == NULL) ... else of vy*/
  /* End of cleaning variable vy */
  } /*CHECKSCALAR(len(rx)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  if((PyObject *)capi_rx_tmp!=rx_capi) {
    Py_XDECREF(capi_rx_tmp); }
  }  /*if (capi_rx_tmp == NULL) ... else of rx*/
  /* End of cleaning variable rx */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************* end of vv_update_positions *************************/

/**************************** vv_update_velocities ****************************/
static char doc_f2py_rout_pymd_mymd_vv_update_velocities[] = "\
vv_update_velocities(vx,vy,vz,ax,ay,az,dt,[n])\n\nWrapper for ``vv_update_velocities``.\
\n\nParameters\n----------\n"
"vx : in/output rank-1 array('f') with bounds (n)\n"
"vy : in/output rank-1 array('f') with bounds (n)\n"
"vz : in/output rank-1 array('f') with bounds (n)\n"
"ax : input rank-1 array('f') with bounds (n)\n"
"ay : input rank-1 array('f') with bounds (n)\n"
"az : input rank-1 array('f') with bounds (n)\n"
"dt : input float\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(vx)";
/*  */
static PyObject *f2py_rout_pymd_mymd_vv_update_velocities(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  float *vx = NULL;
  npy_intp vx_Dims[1] = {-1};
  const int vx_Rank = 1;
  PyArrayObject *capi_vx_tmp = NULL;
  int capi_vx_intent = 0;
  PyObject *vx_capi = Py_None;
  float *vy = NULL;
  npy_intp vy_Dims[1] = {-1};
  const int vy_Rank = 1;
  PyArrayObject *capi_vy_tmp = NULL;
  int capi_vy_intent = 0;
  PyObject *vy_capi = Py_None;
  float *vz = NULL;
  npy_intp vz_Dims[1] = {-1};
  const int vz_Rank = 1;
  PyArrayObject *capi_vz_tmp = NULL;
  int capi_vz_intent = 0;
  PyObject *vz_capi = Py_None;
  float *ax = NULL;
  npy_intp ax_Dims[1] = {-1};
  const int ax_Rank = 1;
  PyArrayObject *capi_ax_tmp = NULL;
  int capi_ax_intent = 0;
  PyObject *ax_capi = Py_None;
  float *ay = NULL;
  npy_intp ay_Dims[1] = {-1};
  const int ay_Rank = 1;
  PyArrayObject *capi_ay_tmp = NULL;
  int capi_ay_intent = 0;
  PyObject *ay_capi = Py_None;
  float *az = NULL;
  npy_intp az_Dims[1] = {-1};
  const int az_Rank = 1;
  PyArrayObject *capi_az_tmp = NULL;
  int capi_az_intent = 0;
  PyObject *az_capi = Py_None;
  float dt = 0;
  PyObject *dt_capi = Py_None;
  static char *capi_kwlist[] = {"vx","vy","vz","ax","ay","az","dt","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|O:pymd.mymd.vv_update_velocities",\
    capi_kwlist,&vx_capi,&vy_capi,&vz_capi,&ax_capi,&ay_capi,&az_capi,&dt_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable vx */
  ;
  capi_vx_intent |= F2PY_INTENT_INOUT;
  capi_vx_tmp = array_from_pyobj(NPY_FLOAT,vx_Dims,vx_Rank,capi_vx_intent,vx_capi);
  if (capi_vx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 1st argument `vx' of pymd.mymd.vv_update_velocities to C/Fortran array" );
  } else {
    vx = (float *)(PyArray_DATA(capi_vx_tmp));

  /* Processing variable dt */
    f2py_success = float_from_pyobj(&dt,dt_capi,"pymd.mymd.vv_update_velocities() 7th argument (dt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(vx); else
    f2py_success = int_from_pyobj(&n,n_capi,"pymd.mymd.vv_update_velocities() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(vx)>=n,"len(vx)>=n","1st keyword n","vv_update_velocities:n=%d",n) {
  /* Processing variable vy */
  vy_Dims[0]=n;
  capi_vy_intent |= F2PY_INTENT_INOUT;
  capi_vy_tmp = array_from_pyobj(NPY_FLOAT,vy_Dims,vy_Rank,capi_vy_intent,vy_capi);
  if (capi_vy_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 2nd argument `vy' of pymd.mymd.vv_update_velocities to C/Fortran array" );
  } else {
    vy = (float *)(PyArray_DATA(capi_vy_tmp));

  /* Processing variable vz */
  vz_Dims[0]=n;
  capi_vz_intent |= F2PY_INTENT_INOUT;
  capi_vz_tmp = array_from_pyobj(NPY_FLOAT,vz_Dims,vz_Rank,capi_vz_intent,vz_capi);
  if (capi_vz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 3rd argument `vz' of pymd.mymd.vv_update_velocities to C/Fortran array" );
  } else {
    vz = (float *)(PyArray_DATA(capi_vz_tmp));

  /* Processing variable ay */
  ay_Dims[0]=n;
  capi_ay_intent |= F2PY_INTENT_IN;
  capi_ay_tmp = array_from_pyobj(NPY_FLOAT,ay_Dims,ay_Rank,capi_ay_intent,ay_capi);
  if (capi_ay_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 5th argument `ay' of pymd.mymd.vv_update_velocities to C/Fortran array" );
  } else {
    ay = (float *)(PyArray_DATA(capi_ay_tmp));

  /* Processing variable ax */
  ax_Dims[0]=n;
  capi_ax_intent |= F2PY_INTENT_IN;
  capi_ax_tmp = array_from_pyobj(NPY_FLOAT,ax_Dims,ax_Rank,capi_ax_intent,ax_capi);
  if (capi_ax_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 4th argument `ax' of pymd.mymd.vv_update_velocities to C/Fortran array" );
  } else {
    ax = (float *)(PyArray_DATA(capi_ax_tmp));

  /* Processing variable az */
  az_Dims[0]=n;
  capi_az_intent |= F2PY_INTENT_IN;
  capi_az_tmp = array_from_pyobj(NPY_FLOAT,az_Dims,az_Rank,capi_az_intent,az_capi);
  if (capi_az_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 6th argument `az' of pymd.mymd.vv_update_velocities to C/Fortran array" );
  } else {
    az = (float *)(PyArray_DATA(capi_az_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,vx,vy,vz,ax,ay,az,&dt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_az_tmp!=az_capi) {
    Py_XDECREF(capi_az_tmp); }
  }  /*if (capi_az_tmp == NULL) ... else of az*/
  /* End of cleaning variable az */
  if((PyObject *)capi_ax_tmp!=ax_capi) {
    Py_XDECREF(capi_ax_tmp); }
  }  /*if (capi_ax_tmp == NULL) ... else of ax*/
  /* End of cleaning variable ax */
  if((PyObject *)capi_ay_tmp!=ay_capi) {
    Py_XDECREF(capi_ay_tmp); }
  }  /*if (capi_ay_tmp == NULL) ... else of ay*/
  /* End of cleaning variable ay */
  if((PyObject *)capi_vz_tmp!=vz_capi) {
    Py_XDECREF(capi_vz_tmp); }
  }  /*if (capi_vz_tmp == NULL) ... else of vz*/
  /* End of cleaning variable vz */
  if((PyObject *)capi_vy_tmp!=vy_capi) {
    Py_XDECREF(capi_vy_tmp); }
  }  /*if (capi_vy_tmp == NULL) ... else of vy*/
  /* End of cleaning variable vy */
  } /*CHECKSCALAR(len(vx)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  if((PyObject *)capi_vx_tmp!=vx_capi) {
    Py_XDECREF(capi_vx_tmp); }
  }  /*if (capi_vx_tmp == NULL) ... else of vx*/
  /* End of cleaning variable vx */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of vv_update_velocities ************************/

/*********************************** move0 ***********************************/
static char doc_f2py_rout_pymd_mymd_move0[] = "\
move0 = move0(rx,ry,rz,vx,vy,vz,ax,ay,az,dt,ntimesteps,[n])\n\nWrapper for ``move0``.\
\n\nParameters\n----------\n"
"rx : in/output rank-1 array('f') with bounds (n)\n"
"ry : in/output rank-1 array('f') with bounds (n)\n"
"rz : in/output rank-1 array('f') with bounds (n)\n"
"vx : in/output rank-1 array('f') with bounds (n)\n"
"vy : in/output rank-1 array('f') with bounds (n)\n"
"vz : in/output rank-1 array('f') with bounds (n)\n"
"ax : in/output rank-1 array('f') with bounds (n)\n"
"ay : in/output rank-1 array('f') with bounds (n)\n"
"az : in/output rank-1 array('f') with bounds (n)\n"
"dt : input float\n"
"ntimesteps : input int\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(rx)\n"
"\nReturns\n-------\n"
"move0 : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_pymd_mymd_move0(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float move0 = 0;
  int n = 0;
  PyObject *n_capi = Py_None;
  float *rx = NULL;
  npy_intp rx_Dims[1] = {-1};
  const int rx_Rank = 1;
  PyArrayObject *capi_rx_tmp = NULL;
  int capi_rx_intent = 0;
  PyObject *rx_capi = Py_None;
  float *ry = NULL;
  npy_intp ry_Dims[1] = {-1};
  const int ry_Rank = 1;
  PyArrayObject *capi_ry_tmp = NULL;
  int capi_ry_intent = 0;
  PyObject *ry_capi = Py_None;
  float *rz = NULL;
  npy_intp rz_Dims[1] = {-1};
  const int rz_Rank = 1;
  PyArrayObject *capi_rz_tmp = NULL;
  int capi_rz_intent = 0;
  PyObject *rz_capi = Py_None;
  float *vx = NULL;
  npy_intp vx_Dims[1] = {-1};
  const int vx_Rank = 1;
  PyArrayObject *capi_vx_tmp = NULL;
  int capi_vx_intent = 0;
  PyObject *vx_capi = Py_None;
  float *vy = NULL;
  npy_intp vy_Dims[1] = {-1};
  const int vy_Rank = 1;
  PyArrayObject *capi_vy_tmp = NULL;
  int capi_vy_intent = 0;
  PyObject *vy_capi = Py_None;
  float *vz = NULL;
  npy_intp vz_Dims[1] = {-1};
  const int vz_Rank = 1;
  PyArrayObject *capi_vz_tmp = NULL;
  int capi_vz_intent = 0;
  PyObject *vz_capi = Py_None;
  float *ax = NULL;
  npy_intp ax_Dims[1] = {-1};
  const int ax_Rank = 1;
  PyArrayObject *capi_ax_tmp = NULL;
  int capi_ax_intent = 0;
  PyObject *ax_capi = Py_None;
  float *ay = NULL;
  npy_intp ay_Dims[1] = {-1};
  const int ay_Rank = 1;
  PyArrayObject *capi_ay_tmp = NULL;
  int capi_ay_intent = 0;
  PyObject *ay_capi = Py_None;
  float *az = NULL;
  npy_intp az_Dims[1] = {-1};
  const int az_Rank = 1;
  PyArrayObject *capi_az_tmp = NULL;
  int capi_az_intent = 0;
  PyObject *az_capi = Py_None;
  float dt = 0;
  PyObject *dt_capi = Py_None;
  int ntimesteps = 0;
  PyObject *ntimesteps_capi = Py_None;
  static char *capi_kwlist[] = {"rx","ry","rz","vx","vy","vz","ax","ay","az","dt","ntimesteps","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|O:pymd.mymd.move0",\
    capi_kwlist,&rx_capi,&ry_capi,&rz_capi,&vx_capi,&vy_capi,&vz_capi,&ax_capi,&ay_capi,&az_capi,&dt_capi,&ntimesteps_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rx */
  ;
  capi_rx_intent |= F2PY_INTENT_INOUT;
  capi_rx_tmp = array_from_pyobj(NPY_FLOAT,rx_Dims,rx_Rank,capi_rx_intent,rx_capi);
  if (capi_rx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 1st argument `rx' of pymd.mymd.move0 to C/Fortran array" );
  } else {
    rx = (float *)(PyArray_DATA(capi_rx_tmp));

  /* Processing variable move0 */
  /* Processing variable dt */
    f2py_success = float_from_pyobj(&dt,dt_capi,"pymd.mymd.move0() 10th argument (dt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ntimesteps */
    f2py_success = int_from_pyobj(&ntimesteps,ntimesteps_capi,"pymd.mymd.move0() 11st argument (ntimesteps) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(rx); else
    f2py_success = int_from_pyobj(&n,n_capi,"pymd.mymd.move0() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(rx)>=n,"len(rx)>=n","1st keyword n","move0:n=%d",n) {
  /* Processing variable vz */
  vz_Dims[0]=n;
  capi_vz_intent |= F2PY_INTENT_INOUT;
  capi_vz_tmp = array_from_pyobj(NPY_FLOAT,vz_Dims,vz_Rank,capi_vz_intent,vz_capi);
  if (capi_vz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 6th argument `vz' of pymd.mymd.move0 to C/Fortran array" );
  } else {
    vz = (float *)(PyArray_DATA(capi_vz_tmp));

  /* Processing variable ay */
  ay_Dims[0]=n;
  capi_ay_intent |= F2PY_INTENT_INOUT;
  capi_ay_tmp = array_from_pyobj(NPY_FLOAT,ay_Dims,ay_Rank,capi_ay_intent,ay_capi);
  if (capi_ay_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 8th argument `ay' of pymd.mymd.move0 to C/Fortran array" );
  } else {
    ay = (float *)(PyArray_DATA(capi_ay_tmp));

  /* Processing variable rz */
  rz_Dims[0]=n;
  capi_rz_intent |= F2PY_INTENT_INOUT;
  capi_rz_tmp = array_from_pyobj(NPY_FLOAT,rz_Dims,rz_Rank,capi_rz_intent,rz_capi);
  if (capi_rz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 3rd argument `rz' of pymd.mymd.move0 to C/Fortran array" );
  } else {
    rz = (float *)(PyArray_DATA(capi_rz_tmp));

  /* Processing variable vx */
  vx_Dims[0]=n;
  capi_vx_intent |= F2PY_INTENT_INOUT;
  capi_vx_tmp = array_from_pyobj(NPY_FLOAT,vx_Dims,vx_Rank,capi_vx_intent,vx_capi);
  if (capi_vx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 4th argument `vx' of pymd.mymd.move0 to C/Fortran array" );
  } else {
    vx = (float *)(PyArray_DATA(capi_vx_tmp));

  /* Processing variable vy */
  vy_Dims[0]=n;
  capi_vy_intent |= F2PY_INTENT_INOUT;
  capi_vy_tmp = array_from_pyobj(NPY_FLOAT,vy_Dims,vy_Rank,capi_vy_intent,vy_capi);
  if (capi_vy_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 5th argument `vy' of pymd.mymd.move0 to C/Fortran array" );
  } else {
    vy = (float *)(PyArray_DATA(capi_vy_tmp));

  /* Processing variable ax */
  ax_Dims[0]=n;
  capi_ax_intent |= F2PY_INTENT_INOUT;
  capi_ax_tmp = array_from_pyobj(NPY_FLOAT,ax_Dims,ax_Rank,capi_ax_intent,ax_capi);
  if (capi_ax_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 7th argument `ax' of pymd.mymd.move0 to C/Fortran array" );
  } else {
    ax = (float *)(PyArray_DATA(capi_ax_tmp));

  /* Processing variable ry */
  ry_Dims[0]=n;
  capi_ry_intent |= F2PY_INTENT_INOUT;
  capi_ry_tmp = array_from_pyobj(NPY_FLOAT,ry_Dims,ry_Rank,capi_ry_intent,ry_capi);
  if (capi_ry_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 2nd argument `ry' of pymd.mymd.move0 to C/Fortran array" );
  } else {
    ry = (float *)(PyArray_DATA(capi_ry_tmp));

  /* Processing variable az */
  az_Dims[0]=n;
  capi_az_intent |= F2PY_INTENT_INOUT;
  capi_az_tmp = array_from_pyobj(NPY_FLOAT,az_Dims,az_Rank,capi_az_intent,az_capi);
  if (capi_az_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 9th argument `az' of pymd.mymd.move0 to C/Fortran array" );
  } else {
    az = (float *)(PyArray_DATA(capi_az_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&move0,&n,rx,ry,rz,vx,vy,vz,ax,ay,az,&dt,&ntimesteps);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",move0);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_az_tmp!=az_capi) {
    Py_XDECREF(capi_az_tmp); }
  }  /*if (capi_az_tmp == NULL) ... else of az*/
  /* End of cleaning variable az */
  if((PyObject *)capi_ry_tmp!=ry_capi) {
    Py_XDECREF(capi_ry_tmp); }
  }  /*if (capi_ry_tmp == NULL) ... else of ry*/
  /* End of cleaning variable ry */
  if((PyObject *)capi_ax_tmp!=ax_capi) {
    Py_XDECREF(capi_ax_tmp); }
  }  /*if (capi_ax_tmp == NULL) ... else of ax*/
  /* End of cleaning variable ax */
  if((PyObject *)capi_vy_tmp!=vy_capi) {
    Py_XDECREF(capi_vy_tmp); }
  }  /*if (capi_vy_tmp == NULL) ... else of vy*/
  /* End of cleaning variable vy */
  if((PyObject *)capi_vx_tmp!=vx_capi) {
    Py_XDECREF(capi_vx_tmp); }
  }  /*if (capi_vx_tmp == NULL) ... else of vx*/
  /* End of cleaning variable vx */
  if((PyObject *)capi_rz_tmp!=rz_capi) {
    Py_XDECREF(capi_rz_tmp); }
  }  /*if (capi_rz_tmp == NULL) ... else of rz*/
  /* End of cleaning variable rz */
  if((PyObject *)capi_ay_tmp!=ay_capi) {
    Py_XDECREF(capi_ay_tmp); }
  }  /*if (capi_ay_tmp == NULL) ... else of ay*/
  /* End of cleaning variable ay */
  if((PyObject *)capi_vz_tmp!=vz_capi) {
    Py_XDECREF(capi_vz_tmp); }
  }  /*if (capi_vz_tmp == NULL) ... else of vz*/
  /* End of cleaning variable vz */
  } /*CHECKSCALAR(len(rx)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of ntimesteps*/
  /* End of cleaning variable ntimesteps */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  /* End of cleaning variable move0 */
  if((PyObject *)capi_rx_tmp!=rx_capi) {
    Py_XDECREF(capi_rx_tmp); }
  }  /*if (capi_rx_tmp == NULL) ... else of rx*/
  /* End of cleaning variable rx */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of move0 ********************************/

/*********************** vv_update_velocities_positions ***********************/
static char doc_f2py_rout_pymd_mymd_vv_update_velocities_positions[] = "\
vv_update_velocities_positions(rx,ry,rz,vx,vy,vz,ax,ay,az,dt,[n])\n\nWrapper for ``vv_update_velocities_positions``.\
\n\nParameters\n----------\n"
"rx : in/output rank-1 array('f') with bounds (n)\n"
"ry : in/output rank-1 array('f') with bounds (n)\n"
"rz : in/output rank-1 array('f') with bounds (n)\n"
"vx : in/output rank-1 array('f') with bounds (n)\n"
"vy : in/output rank-1 array('f') with bounds (n)\n"
"vz : in/output rank-1 array('f') with bounds (n)\n"
"ax : input rank-1 array('f') with bounds (n)\n"
"ay : input rank-1 array('f') with bounds (n)\n"
"az : input rank-1 array('f') with bounds (n)\n"
"dt : input float\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(rx)";
/*  */
static PyObject *f2py_rout_pymd_mymd_vv_update_velocities_positions(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  float *rx = NULL;
  npy_intp rx_Dims[1] = {-1};
  const int rx_Rank = 1;
  PyArrayObject *capi_rx_tmp = NULL;
  int capi_rx_intent = 0;
  PyObject *rx_capi = Py_None;
  float *ry = NULL;
  npy_intp ry_Dims[1] = {-1};
  const int ry_Rank = 1;
  PyArrayObject *capi_ry_tmp = NULL;
  int capi_ry_intent = 0;
  PyObject *ry_capi = Py_None;
  float *rz = NULL;
  npy_intp rz_Dims[1] = {-1};
  const int rz_Rank = 1;
  PyArrayObject *capi_rz_tmp = NULL;
  int capi_rz_intent = 0;
  PyObject *rz_capi = Py_None;
  float *vx = NULL;
  npy_intp vx_Dims[1] = {-1};
  const int vx_Rank = 1;
  PyArrayObject *capi_vx_tmp = NULL;
  int capi_vx_intent = 0;
  PyObject *vx_capi = Py_None;
  float *vy = NULL;
  npy_intp vy_Dims[1] = {-1};
  const int vy_Rank = 1;
  PyArrayObject *capi_vy_tmp = NULL;
  int capi_vy_intent = 0;
  PyObject *vy_capi = Py_None;
  float *vz = NULL;
  npy_intp vz_Dims[1] = {-1};
  const int vz_Rank = 1;
  PyArrayObject *capi_vz_tmp = NULL;
  int capi_vz_intent = 0;
  PyObject *vz_capi = Py_None;
  float *ax = NULL;
  npy_intp ax_Dims[1] = {-1};
  const int ax_Rank = 1;
  PyArrayObject *capi_ax_tmp = NULL;
  int capi_ax_intent = 0;
  PyObject *ax_capi = Py_None;
  float *ay = NULL;
  npy_intp ay_Dims[1] = {-1};
  const int ay_Rank = 1;
  PyArrayObject *capi_ay_tmp = NULL;
  int capi_ay_intent = 0;
  PyObject *ay_capi = Py_None;
  float *az = NULL;
  npy_intp az_Dims[1] = {-1};
  const int az_Rank = 1;
  PyArrayObject *capi_az_tmp = NULL;
  int capi_az_intent = 0;
  PyObject *az_capi = Py_None;
  float dt = 0;
  PyObject *dt_capi = Py_None;
  static char *capi_kwlist[] = {"rx","ry","rz","vx","vy","vz","ax","ay","az","dt","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO|O:pymd.mymd.vv_update_velocities_positions",\
    capi_kwlist,&rx_capi,&ry_capi,&rz_capi,&vx_capi,&vy_capi,&vz_capi,&ax_capi,&ay_capi,&az_capi,&dt_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rx */
  ;
  capi_rx_intent |= F2PY_INTENT_INOUT;
  capi_rx_tmp = array_from_pyobj(NPY_FLOAT,rx_Dims,rx_Rank,capi_rx_intent,rx_capi);
  if (capi_rx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 1st argument `rx' of pymd.mymd.vv_update_velocities_positions to C/Fortran array" );
  } else {
    rx = (float *)(PyArray_DATA(capi_rx_tmp));

  /* Processing variable dt */
    f2py_success = float_from_pyobj(&dt,dt_capi,"pymd.mymd.vv_update_velocities_positions() 10th argument (dt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(rx); else
    f2py_success = int_from_pyobj(&n,n_capi,"pymd.mymd.vv_update_velocities_positions() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(rx)>=n,"len(rx)>=n","1st keyword n","vv_update_velocities_positions:n=%d",n) {
  /* Processing variable vy */
  vy_Dims[0]=n;
  capi_vy_intent |= F2PY_INTENT_INOUT;
  capi_vy_tmp = array_from_pyobj(NPY_FLOAT,vy_Dims,vy_Rank,capi_vy_intent,vy_capi);
  if (capi_vy_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 5th argument `vy' of pymd.mymd.vv_update_velocities_positions to C/Fortran array" );
  } else {
    vy = (float *)(PyArray_DATA(capi_vy_tmp));

  /* Processing variable vz */
  vz_Dims[0]=n;
  capi_vz_intent |= F2PY_INTENT_INOUT;
  capi_vz_tmp = array_from_pyobj(NPY_FLOAT,vz_Dims,vz_Rank,capi_vz_intent,vz_capi);
  if (capi_vz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 6th argument `vz' of pymd.mymd.vv_update_velocities_positions to C/Fortran array" );
  } else {
    vz = (float *)(PyArray_DATA(capi_vz_tmp));

  /* Processing variable ay */
  ay_Dims[0]=n;
  capi_ay_intent |= F2PY_INTENT_IN;
  capi_ay_tmp = array_from_pyobj(NPY_FLOAT,ay_Dims,ay_Rank,capi_ay_intent,ay_capi);
  if (capi_ay_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 8th argument `ay' of pymd.mymd.vv_update_velocities_positions to C/Fortran array" );
  } else {
    ay = (float *)(PyArray_DATA(capi_ay_tmp));

  /* Processing variable ax */
  ax_Dims[0]=n;
  capi_ax_intent |= F2PY_INTENT_IN;
  capi_ax_tmp = array_from_pyobj(NPY_FLOAT,ax_Dims,ax_Rank,capi_ax_intent,ax_capi);
  if (capi_ax_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 7th argument `ax' of pymd.mymd.vv_update_velocities_positions to C/Fortran array" );
  } else {
    ax = (float *)(PyArray_DATA(capi_ax_tmp));

  /* Processing variable ry */
  ry_Dims[0]=n;
  capi_ry_intent |= F2PY_INTENT_INOUT;
  capi_ry_tmp = array_from_pyobj(NPY_FLOAT,ry_Dims,ry_Rank,capi_ry_intent,ry_capi);
  if (capi_ry_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 2nd argument `ry' of pymd.mymd.vv_update_velocities_positions to C/Fortran array" );
  } else {
    ry = (float *)(PyArray_DATA(capi_ry_tmp));

  /* Processing variable az */
  az_Dims[0]=n;
  capi_az_intent |= F2PY_INTENT_IN;
  capi_az_tmp = array_from_pyobj(NPY_FLOAT,az_Dims,az_Rank,capi_az_intent,az_capi);
  if (capi_az_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 9th argument `az' of pymd.mymd.vv_update_velocities_positions to C/Fortran array" );
  } else {
    az = (float *)(PyArray_DATA(capi_az_tmp));

  /* Processing variable rz */
  rz_Dims[0]=n;
  capi_rz_intent |= F2PY_INTENT_INOUT;
  capi_rz_tmp = array_from_pyobj(NPY_FLOAT,rz_Dims,rz_Rank,capi_rz_intent,rz_capi);
  if (capi_rz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 3rd argument `rz' of pymd.mymd.vv_update_velocities_positions to C/Fortran array" );
  } else {
    rz = (float *)(PyArray_DATA(capi_rz_tmp));

  /* Processing variable vx */
  vx_Dims[0]=n;
  capi_vx_intent |= F2PY_INTENT_INOUT;
  capi_vx_tmp = array_from_pyobj(NPY_FLOAT,vx_Dims,vx_Rank,capi_vx_intent,vx_capi);
  if (capi_vx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 4th argument `vx' of pymd.mymd.vv_update_velocities_positions to C/Fortran array" );
  } else {
    vx = (float *)(PyArray_DATA(capi_vx_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,rx,ry,rz,vx,vy,vz,ax,ay,az,&dt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_vx_tmp!=vx_capi) {
    Py_XDECREF(capi_vx_tmp); }
  }  /*if (capi_vx_tmp == NULL) ... else of vx*/
  /* End of cleaning variable vx */
  if((PyObject *)capi_rz_tmp!=rz_capi) {
    Py_XDECREF(capi_rz_tmp); }
  }  /*if (capi_rz_tmp == NULL) ... else of rz*/
  /* End of cleaning variable rz */
  if((PyObject *)capi_az_tmp!=az_capi) {
    Py_XDECREF(capi_az_tmp); }
  }  /*if (capi_az_tmp == NULL) ... else of az*/
  /* End of cleaning variable az */
  if((PyObject *)capi_ry_tmp!=ry_capi) {
    Py_XDECREF(capi_ry_tmp); }
  }  /*if (capi_ry_tmp == NULL) ... else of ry*/
  /* End of cleaning variable ry */
  if((PyObject *)capi_ax_tmp!=ax_capi) {
    Py_XDECREF(capi_ax_tmp); }
  }  /*if (capi_ax_tmp == NULL) ... else of ax*/
  /* End of cleaning variable ax */
  if((PyObject *)capi_ay_tmp!=ay_capi) {
    Py_XDECREF(capi_ay_tmp); }
  }  /*if (capi_ay_tmp == NULL) ... else of ay*/
  /* End of cleaning variable ay */
  if((PyObject *)capi_vz_tmp!=vz_capi) {
    Py_XDECREF(capi_vz_tmp); }
  }  /*if (capi_vz_tmp == NULL) ... else of vz*/
  /* End of cleaning variable vz */
  if((PyObject *)capi_vy_tmp!=vy_capi) {
    Py_XDECREF(capi_vy_tmp); }
  }  /*if (capi_vy_tmp == NULL) ... else of vy*/
  /* End of cleaning variable vy */
  } /*CHECKSCALAR(len(rx)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  if((PyObject *)capi_rx_tmp!=rx_capi) {
    Py_XDECREF(capi_rx_tmp); }
  }  /*if (capi_rx_tmp == NULL) ... else of rx*/
  /* End of cleaning variable rx */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************* end of vv_update_velocities_positions *******************/

/************************************ move ************************************/
static char doc_f2py_rout_pymd_mymd_move[] = "\
move = move(rx,ry,rz,vx,vy,vz,ax,ay,az,dt,ntimesteps,[n])\n\nWrapper for ``move``.\
\n\nParameters\n----------\n"
"rx : in/output rank-1 array('f') with bounds (n)\n"
"ry : in/output rank-1 array('f') with bounds (n)\n"
"rz : in/output rank-1 array('f') with bounds (n)\n"
"vx : in/output rank-1 array('f') with bounds (n)\n"
"vy : in/output rank-1 array('f') with bounds (n)\n"
"vz : in/output rank-1 array('f') with bounds (n)\n"
"ax : in/output rank-1 array('f') with bounds (n)\n"
"ay : in/output rank-1 array('f') with bounds (n)\n"
"az : in/output rank-1 array('f') with bounds (n)\n"
"dt : input float\n"
"ntimesteps : input int\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(rx)\n"
"\nReturns\n-------\n"
"move : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_pymd_mymd_move(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float move = 0;
  int n = 0;
  PyObject *n_capi = Py_None;
  float *rx = NULL;
  npy_intp rx_Dims[1] = {-1};
  const int rx_Rank = 1;
  PyArrayObject *capi_rx_tmp = NULL;
  int capi_rx_intent = 0;
  PyObject *rx_capi = Py_None;
  float *ry = NULL;
  npy_intp ry_Dims[1] = {-1};
  const int ry_Rank = 1;
  PyArrayObject *capi_ry_tmp = NULL;
  int capi_ry_intent = 0;
  PyObject *ry_capi = Py_None;
  float *rz = NULL;
  npy_intp rz_Dims[1] = {-1};
  const int rz_Rank = 1;
  PyArrayObject *capi_rz_tmp = NULL;
  int capi_rz_intent = 0;
  PyObject *rz_capi = Py_None;
  float *vx = NULL;
  npy_intp vx_Dims[1] = {-1};
  const int vx_Rank = 1;
  PyArrayObject *capi_vx_tmp = NULL;
  int capi_vx_intent = 0;
  PyObject *vx_capi = Py_None;
  float *vy = NULL;
  npy_intp vy_Dims[1] = {-1};
  const int vy_Rank = 1;
  PyArrayObject *capi_vy_tmp = NULL;
  int capi_vy_intent = 0;
  PyObject *vy_capi = Py_None;
  float *vz = NULL;
  npy_intp vz_Dims[1] = {-1};
  const int vz_Rank = 1;
  PyArrayObject *capi_vz_tmp = NULL;
  int capi_vz_intent = 0;
  PyObject *vz_capi = Py_None;
  float *ax = NULL;
  npy_intp ax_Dims[1] = {-1};
  const int ax_Rank = 1;
  PyArrayObject *capi_ax_tmp = NULL;
  int capi_ax_intent = 0;
  PyObject *ax_capi = Py_None;
  float *ay = NULL;
  npy_intp ay_Dims[1] = {-1};
  const int ay_Rank = 1;
  PyArrayObject *capi_ay_tmp = NULL;
  int capi_ay_intent = 0;
  PyObject *ay_capi = Py_None;
  float *az = NULL;
  npy_intp az_Dims[1] = {-1};
  const int az_Rank = 1;
  PyArrayObject *capi_az_tmp = NULL;
  int capi_az_intent = 0;
  PyObject *az_capi = Py_None;
  float dt = 0;
  PyObject *dt_capi = Py_None;
  int ntimesteps = 0;
  PyObject *ntimesteps_capi = Py_None;
  static char *capi_kwlist[] = {"rx","ry","rz","vx","vy","vz","ax","ay","az","dt","ntimesteps","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|O:pymd.mymd.move",\
    capi_kwlist,&rx_capi,&ry_capi,&rz_capi,&vx_capi,&vy_capi,&vz_capi,&ax_capi,&ay_capi,&az_capi,&dt_capi,&ntimesteps_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rx */
  ;
  capi_rx_intent |= F2PY_INTENT_INOUT;
  capi_rx_tmp = array_from_pyobj(NPY_FLOAT,rx_Dims,rx_Rank,capi_rx_intent,rx_capi);
  if (capi_rx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 1st argument `rx' of pymd.mymd.move to C/Fortran array" );
  } else {
    rx = (float *)(PyArray_DATA(capi_rx_tmp));

  /* Processing variable ntimesteps */
    f2py_success = int_from_pyobj(&ntimesteps,ntimesteps_capi,"pymd.mymd.move() 11st argument (ntimesteps) can't be converted to int");
  if (f2py_success) {
  /* Processing variable dt */
    f2py_success = float_from_pyobj(&dt,dt_capi,"pymd.mymd.move() 10th argument (dt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable move */
  /* Processing variable n */
  if (n_capi == Py_None) n = len(rx); else
    f2py_success = int_from_pyobj(&n,n_capi,"pymd.mymd.move() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(rx)>=n,"len(rx)>=n","1st keyword n","move:n=%d",n) {
  /* Processing variable vz */
  vz_Dims[0]=n;
  capi_vz_intent |= F2PY_INTENT_INOUT;
  capi_vz_tmp = array_from_pyobj(NPY_FLOAT,vz_Dims,vz_Rank,capi_vz_intent,vz_capi);
  if (capi_vz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 6th argument `vz' of pymd.mymd.move to C/Fortran array" );
  } else {
    vz = (float *)(PyArray_DATA(capi_vz_tmp));

  /* Processing variable ay */
  ay_Dims[0]=n;
  capi_ay_intent |= F2PY_INTENT_INOUT;
  capi_ay_tmp = array_from_pyobj(NPY_FLOAT,ay_Dims,ay_Rank,capi_ay_intent,ay_capi);
  if (capi_ay_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 8th argument `ay' of pymd.mymd.move to C/Fortran array" );
  } else {
    ay = (float *)(PyArray_DATA(capi_ay_tmp));

  /* Processing variable rz */
  rz_Dims[0]=n;
  capi_rz_intent |= F2PY_INTENT_INOUT;
  capi_rz_tmp = array_from_pyobj(NPY_FLOAT,rz_Dims,rz_Rank,capi_rz_intent,rz_capi);
  if (capi_rz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 3rd argument `rz' of pymd.mymd.move to C/Fortran array" );
  } else {
    rz = (float *)(PyArray_DATA(capi_rz_tmp));

  /* Processing variable vx */
  vx_Dims[0]=n;
  capi_vx_intent |= F2PY_INTENT_INOUT;
  capi_vx_tmp = array_from_pyobj(NPY_FLOAT,vx_Dims,vx_Rank,capi_vx_intent,vx_capi);
  if (capi_vx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 4th argument `vx' of pymd.mymd.move to C/Fortran array" );
  } else {
    vx = (float *)(PyArray_DATA(capi_vx_tmp));

  /* Processing variable vy */
  vy_Dims[0]=n;
  capi_vy_intent |= F2PY_INTENT_INOUT;
  capi_vy_tmp = array_from_pyobj(NPY_FLOAT,vy_Dims,vy_Rank,capi_vy_intent,vy_capi);
  if (capi_vy_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 5th argument `vy' of pymd.mymd.move to C/Fortran array" );
  } else {
    vy = (float *)(PyArray_DATA(capi_vy_tmp));

  /* Processing variable ax */
  ax_Dims[0]=n;
  capi_ax_intent |= F2PY_INTENT_INOUT;
  capi_ax_tmp = array_from_pyobj(NPY_FLOAT,ax_Dims,ax_Rank,capi_ax_intent,ax_capi);
  if (capi_ax_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 7th argument `ax' of pymd.mymd.move to C/Fortran array" );
  } else {
    ax = (float *)(PyArray_DATA(capi_ax_tmp));

  /* Processing variable ry */
  ry_Dims[0]=n;
  capi_ry_intent |= F2PY_INTENT_INOUT;
  capi_ry_tmp = array_from_pyobj(NPY_FLOAT,ry_Dims,ry_Rank,capi_ry_intent,ry_capi);
  if (capi_ry_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 2nd argument `ry' of pymd.mymd.move to C/Fortran array" );
  } else {
    ry = (float *)(PyArray_DATA(capi_ry_tmp));

  /* Processing variable az */
  az_Dims[0]=n;
  capi_az_intent |= F2PY_INTENT_INOUT;
  capi_az_tmp = array_from_pyobj(NPY_FLOAT,az_Dims,az_Rank,capi_az_intent,az_capi);
  if (capi_az_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pymd_error,"failed in converting 9th argument `az' of pymd.mymd.move to C/Fortran array" );
  } else {
    az = (float *)(PyArray_DATA(capi_az_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&move,&n,rx,ry,rz,vx,vy,vz,ax,ay,az,&dt,&ntimesteps);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",move);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_az_tmp!=az_capi) {
    Py_XDECREF(capi_az_tmp); }
  }  /*if (capi_az_tmp == NULL) ... else of az*/
  /* End of cleaning variable az */
  if((PyObject *)capi_ry_tmp!=ry_capi) {
    Py_XDECREF(capi_ry_tmp); }
  }  /*if (capi_ry_tmp == NULL) ... else of ry*/
  /* End of cleaning variable ry */
  if((PyObject *)capi_ax_tmp!=ax_capi) {
    Py_XDECREF(capi_ax_tmp); }
  }  /*if (capi_ax_tmp == NULL) ... else of ax*/
  /* End of cleaning variable ax */
  if((PyObject *)capi_vy_tmp!=vy_capi) {
    Py_XDECREF(capi_vy_tmp); }
  }  /*if (capi_vy_tmp == NULL) ... else of vy*/
  /* End of cleaning variable vy */
  if((PyObject *)capi_vx_tmp!=vx_capi) {
    Py_XDECREF(capi_vx_tmp); }
  }  /*if (capi_vx_tmp == NULL) ... else of vx*/
  /* End of cleaning variable vx */
  if((PyObject *)capi_rz_tmp!=rz_capi) {
    Py_XDECREF(capi_rz_tmp); }
  }  /*if (capi_rz_tmp == NULL) ... else of rz*/
  /* End of cleaning variable rz */
  if((PyObject *)capi_ay_tmp!=ay_capi) {
    Py_XDECREF(capi_ay_tmp); }
  }  /*if (capi_ay_tmp == NULL) ... else of ay*/
  /* End of cleaning variable ay */
  if((PyObject *)capi_vz_tmp!=vz_capi) {
    Py_XDECREF(capi_vz_tmp); }
  }  /*if (capi_vz_tmp == NULL) ... else of vz*/
  /* End of cleaning variable vz */
  } /*CHECKSCALAR(len(rx)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  /* End of cleaning variable move */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  } /*if (f2py_success) of ntimesteps*/
  /* End of cleaning variable ntimesteps */
  if((PyObject *)capi_rx_tmp!=rx_capi) {
    Py_XDECREF(capi_rx_tmp); }
  }  /*if (capi_rx_tmp == NULL) ... else of rx*/
  /* End of cleaning variable rx */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of move ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_mymd_def[] = {
  {"wp",0,{{-1}},NPY_INT},
  {"lj_pot",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_lj_pot,doc_f2py_rout_pymd_mymd_lj_pot},
  {"lj_pot2",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_lj_pot2,doc_f2py_rout_pymd_mymd_lj_pot2},
  {"Epot",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_Epot,doc_f2py_rout_pymd_mymd_Epot},
  {"Ekin",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_Ekin,doc_f2py_rout_pymd_mymd_Ekin},
  {"lj_force_factor",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_lj_force_factor,doc_f2py_rout_pymd_mymd_lj_force_factor},
  {"compute_accelerations",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_compute_accelerations,doc_f2py_rout_pymd_mymd_compute_accelerations},
  {"vv_update_positions",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_vv_update_positions,doc_f2py_rout_pymd_mymd_vv_update_positions},
  {"vv_update_velocities",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_vv_update_velocities,doc_f2py_rout_pymd_mymd_vv_update_velocities},
  {"move0",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_move0,doc_f2py_rout_pymd_mymd_move0},
  {"vv_update_velocities_positions",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_vv_update_velocities_positions,doc_f2py_rout_pymd_mymd_vv_update_velocities_positions},
  {"move",-1,{{-1}},0,NULL,(void *)f2py_rout_pymd_mymd_move,doc_f2py_rout_pymd_mymd_move},
  {NULL}
};

static void f2py_setup_mymd(char *wp,char *lj_pot,char *lj_pot2,char *Epot,char *Ekin,char *lj_force_factor,char *compute_accelerations,char *vv_update_positions,char *vv_update_velocities,char *move0,char *vv_update_velocities_positions,char *move) {
  int i_f2py=0;
  f2py_mymd_def[i_f2py++].data = wp;
  f2py_mymd_def[i_f2py++].data = lj_pot;
  f2py_mymd_def[i_f2py++].data = lj_pot2;
  f2py_mymd_def[i_f2py++].data = Epot;
  f2py_mymd_def[i_f2py++].data = Ekin;
  f2py_mymd_def[i_f2py++].data = lj_force_factor;
  f2py_mymd_def[i_f2py++].data = compute_accelerations;
  f2py_mymd_def[i_f2py++].data = vv_update_positions;
  f2py_mymd_def[i_f2py++].data = vv_update_velocities;
  f2py_mymd_def[i_f2py++].data = move0;
  f2py_mymd_def[i_f2py++].data = vv_update_velocities_positions;
  f2py_mymd_def[i_f2py++].data = move;
}
extern void F_FUNC(f2pyinitmymd,F2PYINITMYMD)(void (*)(char*,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_mymd(void) {
  F_FUNC(f2pyinitmymd,F2PYINITMYMD)(f2py_setup_mymd);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "pymd",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_pymd(void) {
#else
#define RETVAL
PyMODINIT_FUNC initpymd(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = pymd_module = PyModule_Create(&moduledef);
#else
  m = pymd_module = Py_InitModule("pymd", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module pymd (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'pymd' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  mymd --- wp,lj_pot(),lj_pot2(),Epot(),Ekin(),lj_force_factor(),compute_accelerations(),vv_update_positions(),vv_update_velocities(),move0(),vv_update_velocities_positions(),move()"".");
  PyDict_SetItemString(d, "__doc__", s);
  pymd_error = PyErr_NewException ("pymd.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));











/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "mymd", PyFortranObject_New(f2py_mymd_def,f2py_init_mymd));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"pymd");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
